version: '3.9'
services:
  server:
    build: server/
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_HOST_PORT=5432
    env_file:
      - .env

  gateway:
    build: gateway/
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_HOST=server
      - SHAREIT_SERVER_PORT=8080

  postgres:
    build: .
    ports:
      - "5435:5432"
    env_file:
      - .env
    volumes:
      - shareit_db:/var/lib/postgresql/data

volumes:
  shareit_db: